import os

Import('env')

sources = Glob('asmjit/**/*.cpp', source=True)

asmjit = env.SharedLibrary(target = 'asmjit',
            source = sources,
            CPPDEFINES = {'ASMJIT_BUILD_X86' : ''},
            CPPPATH = Dir('#/test')
)

asmjit_includes = File('CMakeLists.txt').srcnode().get_abspath()
asmjit_includes = os.path.split(asmjit_includes)[0]

env['asmjit'] = asmjit
env['asmjit_includes'] = asmjit_includes

env.Install(Dir('#/bin'), asmjit)
